// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElFooter: typeof import('element-plus/es')['ElFooter'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElProgress: typeof import('element-plus/es')['ElProgress'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    IEpUpload: typeof import('~icons/ep/upload')['default'];
  }
}
